### ISSUE TITLE
Upgrade: integrate cosmovisor

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#226]
- Modify make targets, related bash scripts and docker environment to use cosmovisor
- Modify systemd service and node deployment scripts to use cosmovisor

**Comment by spivachuk** [comment]
## Options for integrating cosmovisor to docker environment

### Non-default dir layout

**General cons:**
- Uncommon dir layout (differs from default layout being used on a node in production and being used by most well-known apps based on cosmos sdk with cosmovisor)

**Upgrade procedure specific cons:**
- Upgrade changes in `cosmovisor` dir are lost after `localnet_stop`/`localnet_start` while `data` dir content remains related to upgraded state (thus env is broken!)
- `data/upgrade-info.json` is on host while `cosmovisor/current/upgrade-info.json` is not


### Mount `config`, `data`, `keyring-test` dirs separately

**General cons:**
- More dirs (like `keyring-test`) may appear in `.dcl` dir on modules set changes or cosmos sdk updates - they may need to be mounted too
- `data` and `keyring-test` dirs will be created beforehand, not by app

**Upgrade procedure specific cons:**
- Upgrade changes in `cosmovisor` dir are lost after `localnet_stop`/`localnet_start` while `data` dir content remains related to upgraded state (thus env is broken!)
- `data/upgrade-info.json` is on host while `cosmovisor/current/upgrade-info.json` is not
- `data` is in bind mount, its backup will be within container


### Build app on `localnet_init` step

**General cons:**
- App is built at an early step (when genesis files are generated)
- App binary exists as multiple copies (one per each node bind mount)

**Upgrade procedure specific cons:** None

**Comment by spivachuk** [comment]
#### NOTES:
- In base docker env the app must be built in node image or beforehand, not in node container (because app is the same over all node containers)
- In test upgrade docker env the old and new apps must be built in node image or beforehand, not in node container (because old/new app is the same over all node containers)
- `current` symlink (created and modified by cosmovisor) can be added to `PATH` (even before creation) in order to have current app executable as command to directly use it for initialization actions and as client (in cosmovisor documentation the app is directly used for these goals)
