### ISSUE TITLE
Validators: Revocation

### ISSUE THREAD

**Issue by ashcherbakov** [zigbee-alliance/distributed-compliance-ledger#41]
Support the following commands:
- https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#remove_validator_node
- https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#propose_remove_validator_node
- https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#approve_remove_validator_node
- https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#unjail_validator_node

Follow instructions from [How To Make Changes in Data Model for Existing Modules](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-make-changes-in-data-model-for-existing-modules) and [How To Add a new Module](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-add-a-new-module).

**Comment by DenisRybas** [comment]
Everything will be implemented as described in ticket (using instructions from [How To Make Changes in Data Model for Existing Modules](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-make-changes-in-data-model-for-existing-modules) and [How To Add a new Module](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-add-a-new-module)) and docs, except https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/docs/transactions.md#unjail_validator_node
The changes for it:
- `unjail_validator_node` will be renamed to `return_validator_node`
- required role `Trustee` will be changed to `NodeAdmin;owner`
- the ability to vote for `unjail`(`return`) of node is removed, because remove does `NodeAdmin;owner` itself

The documentation will be changed in accordance with what is described above

**Comment by abdulla-ashurov** [comment]
Everything will be implemented as described in ticket (using instructions from [How To Make Changes in Data Model for Existing Modules](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-make-changes-in-data-model-for-existing-modules) and [How To Add a new Module](https://github.com/zigbee-alliance/distributed-compliance-ledger/blob/master/README-DEV.md#how-to-add-a-new-module)) and docs, but there will be some changes:

1. The changes for `unjail_validator_node`:

- `unjail_validator_node` will be renamed to `enable_node`

- required role `Trustee` will be changed to `NodeAdmin;owner`

2. The changes for `remove_validator_node`, `propose_remove_validator_node`, `approve_remove_validator_node`:
will be renamed to `disable_node`, `propose_disable_node`, `approve_disable_node`

The docs will be changed in accordance with what is described above

**Corresponding PR:**

- #321
